# Generated by Django 4.0.2 on 2022-03-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_type_teacherporfile_studentporfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentporfile',
            name='dob',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
