# Generated by Django 4.0.2 on 2022-03-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherporfile',
            name='dob',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
