# Generated by Django 4.0.2 on 2022-03-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=100),
        ),
    ]
