# Generated by Django 4.0.2 on 2022-03-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentporfile_dob'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='class_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherporfile'),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('students', models.ManyToManyField(to='accounts.StudentPorfile')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='classes',
            field=models.ManyToManyField(to='courses.Classes'),
        ),
    ]
