# Generated by Django 4.0.2 on 2022-03-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_class_name_courses_instructor_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
    ]
