# Generated by Django 4.0.2 on 2022-03-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_type'),
        ('courses', '0002_remove_courses_class_name_courses_instructor_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.CreateModel(
            name='JoinClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classes')),
                ('students', models.ManyToManyField(to='accounts.StudentPorfile')),
            ],
        ),
    ]
