# Generated by Django 4.0.2 on 2022-03-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_classes_students_joinclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='classes',
            field=models.ManyToManyField(to='courses.JoinClasses'),
        ),
    ]
