# Generated by Django 4.0.2 on 2022-03-29 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_type'),
        ('courses', '0006_coursecontentfile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Home Work', max_length=100)),
                ('question', models.TextField()),
                ('total_marks', models.FloatField()),
                ('due_time', models.CharField(default=datetime.datetime(2022, 4, 2, 2, 0, 22, 27288), max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/HomeworksQuestions')),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.CharField(blank=True, default=datetime.datetime(2022, 3, 30, 2, 0, 22, 27288), max_length=200, null=True)),
                ('submitted_file', models.FileField(blank=True, upload_to='media/Homeworks')),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('answer', models.TextField()),
                ('marks', models.FloatField()),
                ('homework_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentporfile')),
            ],
        ),
    ]
