# Generated by Django 4.0.2 on 2022-03-29 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_homework_homeworksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_time',
            field=models.CharField(default=datetime.datetime(2022, 4, 2, 2, 2, 18, 532645), max_length=200),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_time',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 30, 2, 2, 18, 532645), max_length=200, null=True),
        ),
    ]
