# Generated by Django 4.0.2 on 2022-03-29 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_homework_due_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='instruction',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_time',
            field=models.CharField(default=datetime.datetime(2022, 4, 2, 3, 40, 31, 13188), max_length=200),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_time',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 30, 3, 40, 31, 13188), max_length=200, null=True),
        ),
    ]
