# Generated by Django 4.0.2 on 2022-03-30 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_homework_instruction_alter_homework_due_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontentfile',
            name='title',
            field=models.CharField(default='Content files', max_length=200),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_time',
            field=models.CharField(default=datetime.datetime(2022, 4, 2, 12, 38, 0, 288360), max_length=200),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_time',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 30, 12, 38, 0, 288360), max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CourseContentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_link', models.TextField()),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent')),
            ],
        ),
    ]
