# Generated by Django 4.0.2 on 2022-03-30 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_homeworksubmission_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_time',
            field=models.CharField(default=datetime.datetime(2022, 4, 2, 22, 16, 39, 465630), max_length=200),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_time',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 3, 30, 22, 16, 39, 465630), max_length=200, null=True),
        ),
    ]
