# Generated by Django 4.0.2 on 2022-03-30 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_homework_due_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_time',
            field=models.CharField(default=datetime.datetime(2022, 4, 2, 23, 9, 29, 925312), max_length=200),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
