# Generated by Django 4.0.2 on 2022-03-30 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_homework_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_time',
            field=models.CharField(default=datetime.datetime(2022, 4, 3, 1, 37, 41, 87113), max_length=200),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
