# Generated by Django 4.0.2 on 2022-03-30 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_homework_due_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_time',
            field=models.CharField(default=datetime.datetime(2022, 4, 3, 1, 37, 55, 596768), max_length=200),
        ),
    ]
